name: Hello Everybody
# Workflow triggered by push(es) into the repository
on: [push]

jobs:
  build:
    # Job Name is Greets
    name: Greets
    # This runs on the latest version of Ubuntu Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Hello World
        uses: hello-world-javascript-action@v1
        id: hello
      # This step prints an output (time) from the previous step's action
      - name: Echo The greeting's time
        run: echo 'The time is ${{ steps.hello.outputs.time }}.'
